[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BREK"
authors = [{name = "Eggsteban", email = "esteban.g.jandres@gmail.com"}]
dynamic = ["333.9.1", "BREK software to autotrade and manual trade on Binance Platform"]
